-- backend/prisma/migrations/001_initial/migration.sql
-- Generated by: npx prisma migrate dev --name initial
-- Run via: npx prisma migrate deploy

-- Users
CREATE TABLE "users" (
  "id" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "avatarColor" TEXT NOT NULL DEFAULT '#4F46E5',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- Refresh tokens
CREATE TABLE "refresh_tokens" (
  "id" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "refresh_tokens_token_key" ON "refresh_tokens"("token");

-- Groups
CREATE TABLE "groups" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "emoji" TEXT NOT NULL DEFAULT '💰',
  "inviteCode" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "groups_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "groups_inviteCode_key" ON "groups"("inviteCode");

-- Group members
CREATE TABLE "group_members" (
  "id" TEXT NOT NULL,
  "groupId" TEXT NOT NULL,
  "userId" TEXT,
  "displayName" TEXT NOT NULL,
  "avatarColor" TEXT NOT NULL DEFAULT '#4F46E5',
  "avatarInitials" TEXT NOT NULL,
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "group_members_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "group_members_groupId_userId_key" ON "group_members"("groupId", "userId");

-- Expenses
CREATE TYPE "SplitType" AS ENUM ('EQUAL', 'ITEMIZED', 'CUSTOM');
CREATE TABLE "expenses" (
  "id" TEXT NOT NULL,
  "groupId" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "totalAmount" DOUBLE PRECISION NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'CHF',
  "paidByMemberId" TEXT NOT NULL,
  "splitType" "SplitType" NOT NULL DEFAULT 'EQUAL',
  "receiptImageUrl" TEXT,
  "receiptImageKey" TEXT,
  "ocrConfidence" DOUBLE PRECISION,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "expenses_pkey" PRIMARY KEY ("id")
);

-- Expense items
CREATE TABLE "expense_items" (
  "id" TEXT NOT NULL,
  "expenseId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "ocrRaw" TEXT,
  "ocrConfidence" DOUBLE PRECISION,
  "corrected" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "expense_items_pkey" PRIMARY KEY ("id")
);

-- Item assignments
CREATE TABLE "expense_item_assignments" (
  "id" TEXT NOT NULL,
  "itemId" TEXT NOT NULL,
  "memberId" TEXT NOT NULL,
  CONSTRAINT "expense_item_assignments_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "eia_item_member" ON "expense_item_assignments"("itemId", "memberId");

-- Expense splits
CREATE TABLE "expense_splits" (
  "id" TEXT NOT NULL,
  "expenseId" TEXT NOT NULL,
  "memberId" TEXT NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "settled" BOOLEAN NOT NULL DEFAULT false,
  "settledAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "expense_splits_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "expense_splits_expenseId_memberId_key" ON "expense_splits"("expenseId", "memberId");

-- OCR corrections (training data)
CREATE TABLE "ocr_corrections" (
  "id" TEXT NOT NULL,
  "receiptId" TEXT,
  "ocrRaw" TEXT NOT NULL,
  "ocrPriceRaw" TEXT NOT NULL,
  "correctedName" TEXT NOT NULL,
  "correctedPrice" DOUBLE PRECISION NOT NULL,
  "confidence" DOUBLE PRECISION NOT NULL,
  "vendorHint" TEXT,
  "deviceId" TEXT,
  "appVersion" TEXT,
  "trained" BOOLEAN NOT NULL DEFAULT false,
  "trainingRunId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ocr_corrections_pkey" PRIMARY KEY ("id")
);

-- OCR training runs
CREATE TABLE "ocr_training_runs" (
  "id" TEXT NOT NULL,
  "correctionCount" INTEGER NOT NULL,
  "exportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "datasetUrl" TEXT,
  "notes" TEXT,
  CONSTRAINT "ocr_training_runs_pkey" PRIMARY KEY ("id")
);

-- Foreign keys
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "group_members" ADD CONSTRAINT "gm_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "group_members" ADD CONSTRAINT "gm_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "expenses" ADD CONSTRAINT "exp_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "expenses" ADD CONSTRAINT "exp_paidBy_fkey" FOREIGN KEY ("paidByMemberId") REFERENCES "group_members"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "expense_items" ADD CONSTRAINT "ei_expenseId_fkey" FOREIGN KEY ("expenseId") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "expense_item_assignments" ADD CONSTRAINT "eia_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "expense_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "expense_item_assignments" ADD CONSTRAINT "eia_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "group_members"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "expense_splits" ADD CONSTRAINT "es_expenseId_fkey" FOREIGN KEY ("expenseId") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "expense_splits" ADD CONSTRAINT "es_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "group_members"("id") ON DELETE CASCADE ON UPDATE CASCADE;
